async function updateNowPlaying() {
    try {
        // Fetch data from a local file generated by Snip or similar tool
        const response = await fetch('file:///C:/path/to/snip/nowplaying.txt');
        const text = await response.text();
        
        // Parse the text file (assuming format: Artist - Title)
        const [artist, title] = text.split(' - ');

        document.getElementById('track-name').innerText = title;
        document.getElementById('track-artist').innerText = artist;
        document.getElementById('now-playing').classList.remove('hidden');
    } catch (error) {
        console.error('Error fetching song:', error);
        document.getElementById('now-playing').classList.add('hidden');
    }
}

// Update every 5 seconds
setInterval(updateNowPlaying, 5000);
updateNowPlaying();
